### ISSUE TITLE
Error connecting to target process

### ISSUE THREAD

**Issue by suhasg** [Andrevus/jetbrains-targetprocess-tasks#9]
Using Rubymine

```
Invalid challenge: Basic
org.apache.commons.httpclient.auth.MalformedChallengeException: Invalid challenge: Basic
	at org.apache.commons.httpclient.auth.AuthChallengeParser.extractParams(AuthChallengeParser.java:98)
	at org.apache.commons.httpclient.auth.RFC2617Scheme.processChallenge(RFC2617Scheme.java:94)
	at org.apache.commons.httpclient.auth.BasicScheme.processChallenge(BasicScheme.java:112)
	at org.apache.commons.httpclient.auth.AuthChallengeProcessor.processChallenge(AuthChallengeProcessor.java:162)
	at org.apache.commons.httpclient.HttpMethodDirector.processWWWAuthChallenge(HttpMethodDirector.java:694)
	at org.apache.commons.httpclient.HttpMethodDirector.processAuthenticationResponse(HttpMethodDirector.java:668)
	at org.apache.commons.httpclient.HttpMethodDirector.executeMethod(HttpMethodDirector.java:193)
	at org.apache.commons.httpclient.HttpClient.executeMethod(HttpClient.java:397)
	at org.apache.commons.httpclient.HttpClient.executeMethod(HttpClient.java:323)
	at net.andrevus.jetbrains.tasks.TargetProcessRepository.getIssues(TargetProcessRepository.java:61)
	at com.intellij.tasks.impl.TaskManagerImpl.getIssuesFromRepositories(TaskManagerImpl.java:791)
	at com.intellij.tasks.impl.TaskManagerImpl.getIssues(TaskManagerImpl.java:257)
	at com.intellij.tasks.actions.TaskSearchSupport.getRepositoriesTasks(TaskSearchSupport.java:64)
	at com.intellij.tasks.actions.TaskItemProvider.fetchFromServer(TaskItemProvider.java:155)
	at com.intellij.tasks.actions.TaskItemProvider.lambda$filterElements$0(TaskItemProvider.java:74)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at com.intellij.util.concurrency.SchedulingWrapper$MyScheduledFutureTask.run(SchedulingWrapper.java:237)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)


org.jdom.input.JDOMParseException: Error on line 1: Content is not allowed in prolog.
	at org.jdom.input.SAXBuilder.build(SAXBuilder.java:533)
	at net.andrevus.jetbrains.tasks.TargetProcessRepository.getIssues(TargetProcessRepository.java:69)
	at com.intellij.tasks.impl.TaskManagerImpl.getIssuesFromRepositories(TaskManagerImpl.java:791)
	at com.intellij.tasks.impl.TaskManagerImpl.getIssues(TaskManagerImpl.java:257)
	at com.intellij.tasks.actions.TaskSearchSupport.getRepositoriesTasks(TaskSearchSupport.java:64)
	at com.intellij.tasks.actions.TaskItemProvider.fetchFromServer(TaskItemProvider.java:155)
	at com.intellij.tasks.actions.TaskItemProvider.lambda$filterElements$0(TaskItemProvider.java:74)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at com.intellij.util.concurrency.SchedulingWrapper$MyScheduledFutureTask.run(SchedulingWrapper.java:237)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: org.xml.sax.SAXParseException; lineNumber: 1; columnNumber: 1; Content is not allowed in prolog.
	at org.apache.xerces.util.ErrorHandlerWrapper.createSAXParseException(Unknown Source)
	at org.apache.xerces.util.ErrorHandlerWrapper.fatalError(Unknown Source)
	at org.apache.xerces.impl.XMLErrorReporter.reportError(Unknown Source)
	at org.apache.xerces.impl.XMLErrorReporter.reportError(Unknown Source)
	at org.apache.xerces.impl.XMLErrorReporter.reportError(Unknown Source)
	at org.apache.xerces.impl.XMLScanner.reportFatalError(Unknown Source)
	at org.apache.xerces.impl.XMLDocumentScannerImpl$PrologDispatcher.dispatch(Unknown Source)
	at org.apache.xerces.impl.XMLDocumentFragmentScannerImpl.scanDocument(Unknown Source)
	at org.apache.xerces.parsers.XML11Configuration.parse(Unknown Source)
	at org.apache.xerces.parsers.XML11Configuration.parse(Unknown Source)
	at org.apache.xerces.parsers.XMLParser.parse(Unknown Source)
	at org.apache.xerces.parsers.AbstractSAXParser.parse(Unknown Source)
	at org.apache.xerces.jaxp.SAXParserImpl$JAXPSAXParser.parse(Unknown Source)
	at org.jdom.input.SAXBuilder.build(SAXBuilder.java:518)
	... 11 more
Caused by: org.xml.sax.SAXParseException; lineNumber: 1; columnNumber: 1; Content is not allowed in prolog.
	at org.apache.xerces.util.ErrorHandlerWrapper.createSAXParseException(Unknown Source)
	at org.apache.xerces.util.ErrorHandlerWrapper.fatalError(Unknown Source)
	at org.apache.xerces.impl.XMLErrorReporter.reportError(Unknown Source)
	at org.apache.xerces.impl.XMLErrorReporter.reportError(Unknown Source)
	at org.apache.xerces.impl.XMLErrorReporter.reportError(Unknown Source)
	at org.apache.xerces.impl.XMLScanner.reportFatalError(Unknown Source)
	at org.apache.xerces.impl.XMLDocumentScannerImpl$PrologDispatcher.dispatch(Unknown Source)
	at org.apache.xerces.impl.XMLDocumentFragmentScannerImpl.scanDocument(Unknown Source)
	at org.apache.xerces.parsers.XML11Configuration.parse(Unknown Source)
	at org.apache.xerces.parsers.XML11Configuration.parse(Unknown Source)
	at org.apache.xerces.parsers.XMLParser.parse(Unknown Source)
	at org.apache.xerces.parsers.AbstractSAXParser.parse(Unknown Source)
	at org.apache.xerces.jaxp.SAXParserImpl$JAXPSAXParser.parse(Unknown Source)
	at org.jdom.input.SAXBuilder.build(SAXBuilder.java:518)
	at net.andrevus.jetbrains.tasks.TargetProcessRepository.getIssues(TargetProcessRepository.java:69)
	at com.intellij.tasks.impl.TaskManagerImpl.getIssuesFromRepositories(TaskManagerImpl.java:791)
	at com.intellij.tasks.impl.TaskManagerImpl.getIssues(TaskManagerImpl.java:257)
	at com.intellij.tasks.actions.TaskSearchSupport.getRepositoriesTasks(TaskSearchSupport.java:64)
	at com.intellij.tasks.actions.TaskItemProvider.fetchFromServer(TaskItemProvider.java:155)
	at com.intellij.tasks.actions.TaskItemProvider.lambda$filterElements$0(TaskItemProvider.java:74)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at com.intellij.util.concurrency.SchedulingWrapper$MyScheduledFutureTask.run(SchedulingWrapper.java:237)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

```

**Comment by moledet** [comment]
Invalid challenge: Basic

**Comment by saigkill** [comment]
Currently i  have the same issue. How can i fix it?
